################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

evaluationReportPath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation\704
dataSavePath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation\704
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  Lidar704:   # lidar No.1
    dataPath: D:\Data\CMA_Lidar_Comparison\704\Rayleigh-test
    dataFilenamePattern: .*Lidar.*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 3
    chTag: ['355p', '355s', '532p', '532s', '387', '407', '607', '1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    nMaxBin: 2000   # number of bins
    flagFilenameTime: true

# internal-check
# Below is the struct of `internalChkCfg`, which holds the specific configurations for each lidar.
# Lidar type is configured in the second level (with 1 indention), while the detailed configuration for each lidar is configured in the third level (with 2 indentions).
internalChkCfg:
  Lidar704:
    lidarNo: 9   # lidar number. (see ./docs/lidarList.md)
    chTag: ['355p', '355s', '532p', '532s', '387', '407', '607', '1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1700, 1950]   # [start index, stop index] for background correction
      nPretrigger: 0   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: false   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: true   # Rayleigh fit check
    flagBgNoiseChk: false   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    RayleighChkCfg:
      tRange: '2021-09-23 00:00:00 ~ 2021-09-23 00:30:00'
      wavelength:
        - [532]   # wavelength. (nm)
        - [1064]   # wavelength. (nm)
      fitRange:
        - [12000, 15000]   # Rayleigh fit range. (m)
        - [5700, 7500]   # Rayleigh fit range. (m)
      smoothwindow:
        - [15]
        - [150]
      MieGlue:
        - [0, 0, 1, 0, 0, 0, 0, 0]   # MieGlue * signal ([1, 0.5] * [PSignal, SSignal])
        - [0, 0, 0, 0, 0, 0, 0, 1]   # MieGlue * signal ([1, 0.5] * [PSignal, SSignal])
      hRange:
        - [0, 30000]   # display range. (m)
        - [0, 30000]   # display range. (m)
      sigRange:
        - [1e7, 5e11]   # signal display range. (a.u.)
        - [1e7, 5e11]   # signal display range. (a.u.)
      maxDev:
        - [15]   # maximum relative deviation. (%)
        - [15]   # maximum relative deviation. (%)