################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

resultPath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\AW
dataSavePath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\AW
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  AW:   # lidar No.1
    dataPath: D:\Data\CMA_Lidar_Comparison\internalChk\AW\RayleighFit-test
    dataFilenamePattern: .*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 3
    chTag: ['532p', '532s']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    nMaxBin: 2000   # number of bins

dataVisualCfg:
  AW:
    lidarNo: 3   # lidar number. (see ./docs/lidarList.md)
    chTag: ['532p', '532s']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: -885   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1700, 1800]   # [start index, stop index] for background correction
      nPretrigger: 59   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: 'L0110_overlap.txt'
    tRange: '2021-09-21 00:00:00 ~ 2021-09-21 23:59:00'
    hRange:
      - [0, 15000]
      - [0, 15000]
    sigRange: 
      - [0, 5e10]
      - [0, 0.5e10]
    title:
      - '2021-09-21 AW 532p'
      - '2021-09-21 AW 532s'
    deltaT: 1   # temporal resolution (min)
    markTRange: '2021-09-27 :30:00 ~ 2021-09-21 02:00:00'