################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

resultPath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\AW
dataSavePath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\AW
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  AW:   # lidar No.1
    dataPath: D:\Data\CMA_Lidar_Comparison\internalChk\AW\telecover-test
    dataFilenamePattern: .*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 3
    chTag: ['532p', '532s']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    nMaxBin: 2000   # number of bins

# internal-check
# Below is the struct of `internalChkCfg`, which holds the specific configurations for each lidar.
# Lidar type is configured in the second level (with 1 indention), while the detailed configuration for each lidar is configured in the third level (with 2 indentions).
internalChkCfg:
  AW:
    lidarNo: 3   # lidar number. (see ./docs/lidarList.md)
    chTag: ['532p', '532s']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: -1   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1700, 1800]   # [start index, stop index] for background correction
      nPretrigger: 0   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: 'L0110_overlap.txt'
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: true   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: false   # Rayleigh fit check
    flagBgNoiseChk: false   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    quadrantChkCfg:
      quadrantTime:   # quadrant time (local time) [E-S-W-N-E]
        - '2021-09-16 12:26:00 ~ 2021-09-16 12:27:00'   # east1
        - '2021-09-16 12:35:00 ~ 2021-09-16 12:36:00'   # south
        - '2021-09-16 12:39:00 ~ 2021-09-16 12:40:00'   # west
        - '2021-09-16 12:42:00 ~ 2021-09-16 12:43:00'   # north
        - '2021-09-16 12:26:00 ~ 2021-09-16 12:27:00'   # east2
      hRangeNear:
        - [0, 5000]   # vertical range for near-range behavior to display. (m)
        - [0, 5000]   # vertical range for near-range behavior to display. (m)
      hRangeAll:
          - [0, 10000]   # vertical range for overall behavior to display. (m)
          - [0, 10000]   # vertical range for overall behavior to display. (m)
      normRange:
        - [1500, 2500]   # normalization range. (m)
        - [1500, 2500]   # normalization range. (m)
      rcsDisplayRangeAll:
          - [0, 2e11]   # range of rcs
          - [0, 1e10]   # range of rcs
      normSigDisplayRangeAll:
        - [0, 2e10]   # normalized signal display range. (photon count)
        - [0, 1e10]   # normalized signal display range. (photon count)
      normSigDisplayRangeNear:
        - [5e9, 5e10]   # normalized signal display range. (photon count)
        - [1e9, 1e10]   # normalized signal display range. (photon count)
      smoothwindow:
        - 150   # smoothing window length. (m)
        - 300   # smoothing window length. (m)
      stableThresh: 10   # [%]
      maxDev: 20   # [%]