################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

evaluationReportPath: C:\Users\zhenping\Desktop\lidar_evaluation\report
dataSavePath: C:\Users\zhenping\Desktop\lidar_evaluation\data
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  WH1:   # lidar No.1
    dataPath: D:\Data\1064nm_lidar_comparison\20210918\WHU1064_1
    dataFilenamePattern: .*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 1
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h;
    nMaxBin: 2048   # number of bins
  WH2:   # lidar No.2
    dataPath: D:\Data\1064nm_lidar_comparison\20210918\WHU1064_2
    dataFilenamePattern: .*   # all files
    dataFormat: 2
    chTag: ['1064e']
    nMaxBin: 1300   # number of bins
  DS:   # lidar No.3
    dataPath: D:\Data\1064nm_lidar_comparison\20210909\Dasun-Pol
    dataFilenamePattern: .*   # all files
    dataFormat: 4
    chTag: ['1064p', '1064s']
    nMaxBin: 1300   # number of bins
  REAL:   # lidar No.4
    dataPath: D:\Coding\Matlab\CMA-lidar-evaluation\data\REAL
    dataFilenamePattern: .*   # all files
    dataFormat: 5
    chTag: ['532p', '532s', '607']
    nMaxBin: 2400   # number of bins

# internal-check
# Below is the struct of `internalChkCfg`, which holds the specific configurations for each lidar.
# Lidar type is configured in the second level (with 1 indention), while the detailed configuration for each lidar is configured in the third level (with 2 indentions).
internalChkCfg:
  WH1:
    lidarNo: 12   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1500, 2000]   # [start index, stop index] for background correction
      nPretrigger: 15   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: false   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: false   # Rayleigh fit check
    flagBgNoiseChk: false   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: true   # continuous operation check
    saturationChkCfg:
      tRange:
        - '2021-09-18 20:14:38 ~ 2021-09-18 20:14:50'   # 100% transmission
        - '2021-09-18 20:16:05 ~ 2021-09-18 20:16:08'   # 80% transmission
        - '2021-09-18 20:21:30 ~ 2021-09-18 20:21:38'   # 50% transmission
        - '2021-09-18 20:17:32 ~ 2021-09-18 20:17:40'   # 20% transmission
        - '2021-09-18 20:23:00 ~ 2021-09-18 20:23:10'   # 10% transmission
      sigRange:
        - [1e7, 1e9]
      hRange:
        - [0, 4000]
      normRange:
        - [500, 2000]
      maxDev: [10]   # [%]
      smoothwindow: [300]   # (m)
    RayleighChkCfg:
      tRange: '2021-09-18 20:00:00 ~ 2021-09-18 21:00:00'
      wavelength:
        - [1064]   # wavelength. (nm)
      fitRange:
        - [6000, 7000]   # Rayleigh fit range. (m)
      smoothwindow:
        - [300]
      MieGlue:
        - [1]   # MieGlue * signal ([1, 0.5] * [PSignal, SSignal])
      hRange:
        - [0, 10000]   # display range. (m)
      sigRange:
        - [1e8, 1.4e10]   # signal display range. (a.u.)
      maxDev: [15]   # maximum relative deviation. (%)
    bgNoiseChkCfg:
      closeTRange: '2021-09-18 17:00:00 ~ 2021-09-18 18:00:00'   # cover closed
      randErrCalcWindowLength: 300   # window length for calculating random error. (m)
      bgRange:
        - [0, 1e3]
      hRange:   # background display range. (m)
        - [0, 20000]
    detectRangeChkCfg:
      tRange: '2021-09-18 20:00:00 ~ 2021-09-18 21:00:00'   # temporal integral range for detection ability check
      minSNR: [3]   # minimum SNR
      minHeight: [9000]   # minimum height. (m)
      sigRange:
        - [1, 1e6]
      snrRange:
        - [1e-1, 1e3]
      hRange:
        - [0, 12000]
    contOptChkCfg:
      deltaT: 1   # temporal resolution (min)
      nMinProfile: 1440   # minimum profiles required
      tRange: '2021-09-18 16:36:00 ~ 2021-09-18 20:35:00'
      hRange: [0, 10000]
      cRange:   # color range for Range-corrected signal
        - [0, 1e10]   # channel 1
    quadrantChkCfg:
      quadrantTime:   # quadrant time (local time) [E-S-W-N-E]
        - '2021-09-18 20:14:38 ~ 2021-09-18 20:14:50'   # east1
        - '2021-09-18 20:16:05 ~ 2021-09-18 20:16:08'   # south
        - '2021-09-18 20:17:32 ~ 2021-09-18 20:17:40'   # west
        - '2021-09-18 20:21:30 ~ 2021-09-18 20:21:38'   # north
        - '2021-09-18 20:23:00 ~ 2021-09-18 20:23:10'   # east2
      hRangeNear: [0, 1500]   # vertical range for near-range behavior to display. (m)
      rcsDisplayRangeAll:
        - [0, 1e11]   # range of rcs
      hRangeAll: [0, 5000]   # vertical range for overall behavior to display. (m)
      normRange: [800, 1500]   # normalization range. (m)
      normSigDisplayRangeAll: [0, 1.4e10]   # normalized signal display range. (photon count)
      normSigDisplayRangeNear: [0, 1.4e10]   # normalized signal display range. (photon count)
      smoothwindow: 300   # smoothing window length. (m)
      stableThresh: 10   # [%]
      maxDev: 20   # [%]

# external-check
# Below is the struct of `externalChkCfg`, which was used to inter-compare lidars.
externalChkCfg:
  figVisible: 'on'   # whether display figures
  WH1:
    lidarNo: 12   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    overlapFile: ''
    hOffset: 0   # height offset. (m)
    tOffset: 0   # time offset. (min)
    deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
    bgBins: [1500, 2000]   # [start index, stop index] for background correction
    nPretrigger: 15   # if nPretrigger < 0, move signal up
    bgCorFile: ''   # data file of dark measurement results
  WH2:
    lidarNo: 13   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    fullOverlapHeight: 200   # minimum height with complete overlap. (m)
    overlapFile: ''
    hOffset: 0   # height offset. (m)
    tOffset: 0   # time offset. (min)
    deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
    bgBins: [1200, 1250]   # [start index, stop index] for background correction
    nPretrigger: 0   # if nPretrigger < 0, move signal up
    bgCorFile: ''   # data file of dark measurement results
  flagRangeCmp: false
  flagRCSCmp: false
  flagVDRCmp: false
  flagFernaldCmp: false
  flagRamanCmp: true
  rangeCmpCfg:
    LidarList: ['WH1', 'WH2']   # lidar in comparison (1: standard lidar)
    tRange: '2021-09-18 17:00:38 ~ 2021-09-18 18:00:50'
    hRange: [2000, 3000]
    fitRange: [2200, 2400]
    normRange: [2500, 3000]
    sigRange: [1e8, 1e10]
    sigCompose:
      - [1]   # first lidar
      - [1]   # second lidar
    maxRangeDev: 15   # (m)
  RCSCmpCfg:
    LidarList: ['WH1', 'WH2']
    sigCompose:
      - [1]   # first lidar
      - [1]   # second lidar
    tRange: '2021-09-18 17:00:38 ~ 2021-09-18 18:00:50'
    normRange: [2000, 3000]
    hChkRange:
      - [500, 2000]
      - [2000, 5000]
    maxDev:
      - 10
      - 20
    smoothwindow:
      - [0, 1000, 100]   # Piecewise smoothing: [bottom height, top height, window length]
      - [1000, 10000, 300]
    hRange: [0, 5000]
    sigRange: [1e8, 1e11]
  VDRCmpCfg:
    LidarList: ['WH1', 'WH2']
    vdrCompose:
      - ['532p', '532s', 1, 0]   # first lidar    [pChannel, sChannel, gainRatio, offset]
      - ['532p', '532s', 1, 0]   # second lidar
    tRange: '2021-09-18 17:00:38 ~ 2021-09-18 18:00:50'
    hChkRange:
      - [500, 2000]
      - [2000, 5000]
    maxDev:
      - [10, 10]   # [mean relative deviation, standard relative deviation]
      - [20, 20]
    smoothwindow:
      - [0, 1000, 100]   # Piecewise smoothing: [bottom height, top height, window length]
      - [1000, 10000, 300]
    hRange: [0, 5000]
    vdrRange: [0, 0.4]
  FernaldCmpCfg:
    LidarList: ['WH1', 'WH2']
    wavelength: 1064   # (nm)
    sigCompose:
      - [1]   # first lidar   # ratio for each channel; [1, 0]: 1 * sig_ch1 + 0 * sig_ch2
      - [1]   # second lidar
    tRange: '2021-09-18 17:00:38 ~ 2021-09-18 18:00:50'
    refRange: [5000, 5500]
    refValue: 1e-7   # (m^-1*sr^-1)
    hChkRange:
      - [500, 2000]
      - [2000, 5000]
    maxDev:
      - [20, 20]   # [mean relative deviation, standard relative deviation]
      - [40, 40]
    minBsc: 1e-7   # (m^-1*sr^-1)
    smoothwindow:
      - [0, 1000, 100]   # Piecewise smoothing: [bottom height, top height, window length]
      - [1000, 10000, 300]
    hRange: [0, 7000]
    lidarRatio: 50   # (sr)
    bscRange: [0, 0.5e-5]
    extRange: [0, 2.5e-4]
  RamanCmpCfg:
    LidarList: ['WH1', 'WH2']
    wavelengthMie: 532   # (nm)
    wavelengthRaman: 607   # (nm)
    RamanChTag: ['607', '607']
    MieChCompose:
      - ['532p', '532s', 1]   # Lidar 1: [pChannel, sChannel, gainRatio]
      - ['532p', '532s', 1]
    tRange: '2021-09-18 17:00:38 ~ 2021-09-18 18:00:50'
    refRange: [5000, 5500]
    refValue: 1e-7   # (m^-1*sr^-1)
    hChkRange:
      - [500, 2000]   # height range 1
      - [2000, 5000]   # height range 2
    maxBscDev:
      - [20, 20]   # max bsc dev for height range 1
      - [30, 40]   # max bsc dev for height range 2
    maxExtDev:
      - [25, 25]
      - [40, 40]
    minBsc: 1e-7   # (m^-1*sr^-1)
    smoothwindow:
      - [0, 1000, 100]   # Piecewise smoothing: [bottom height, top height, window length]
      - [1000, 10000, 300]
    hRange: [0, 7000]
    bscRange: [0, 0.5e-5]
    extRange: [0, 2.5e-4]

dataVisualCfg:
  WH1:
    lidarNo: 12   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1500, 2000]   # [start index, stop index] for background correction
      nPretrigger: 15   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    tRange: '2021-09-18 16:36:00 ~ 2021-09-18 20:35:00'
    markTRange: '2021-09-18 18:36:00 ~ 2021-09-18 19:35:00'
    title: ''
    hRange: [0, 10000]
    deltaT: 1   # temporal resolution (min)