resultPath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\DS
dataSavePath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\DS
figFormat: png   # figure format to be exported

dataLoaderCfg:
  DS:   # Dasun
    dataPath: D:\Data\CMA_Lidar_Comparison\internalChk\DS\background-noise-test
    dataFilenamePattern: .*Lidar.*
    dataFormat: 3
    chTag: ['1064p', '1064s']
    nMaxBin: 1250

internalChkCfg:
  DS:
    lidarNo: 9   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064p', '1064s']
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1100, 1200]   # [start index, stop index] for background correction
      nPretrigger: 0   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: false   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: false   # Rayleigh fit check
    flagBgNoiseChk: true   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    bgNoiseChkCfg:
      closeTRange: '2021-09-25 18:07:00 ~ 2021-09-25 18:14:00'   # cover closed
      randErrCalcWindowLength: 300   # window length for calculating random error. (m)
      bgRange:
        - [-1, 2]
        - [-2, 3]
      hRange:   # background display range. (m)
        - [300, 20000]
        - [300, 20000]