resultPath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\DS
dataSavePath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\DS
figFormat: png   # figure format to be exported

dataLoaderCfg:
  DS:   # Dasun
    dataPath: D:\Data\CMA_Lidar_Comparison\internalChk\DS\RayleighFit-test
    dataFilenamePattern: .*Lidar.*
    dataFormat: 3
    chTag: ['1064p', '1064s']
    nMaxBin: 1250

internalChkCfg:
  DS:
    lidarNo: 9   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064p', '1064s']
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1100, 1200]   # [start index, stop index] for background correction
      nPretrigger: 0   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: false   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: true   # Rayleigh fit check
    flagBgNoiseChk: false   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    RayleighChkCfg:
      tRange: '2021-09-27 18:30:00 ~ 2021-09-27 19:02:00'
      wavelength:
        - [1064]   # wavelength. (nm)
      fitRange:
        - [6000, 7000]   # Rayleigh fit range. (m)
      smoothwindow:
        - [300]
      MieGlue:
        - [1, 0]   # MieGlue * signal ([1, 0.5] * [PSignal, SSignal])
      hRange:
        - [0, 15000]   # display range. (m)
      sigRange:
        - [5e8, 1e11]   # signal display range. (a.u.)
      maxDev: [15]   # maximum relative deviation. (%)
      flagLinearFit: true