################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

evaluationReportPath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation\L0110
dataSavePath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation\L0110
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  L0110:   # lidar No.1
    dataPath: D:\Data\CMA_Lidar_Comparison\L0110\RayleighFit_09_21\20210921
    dataFilenamePattern: .*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 3
    chTag: ['532p', '532s']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    nMaxBin: 2048   # number of bins

# internal-check
# Below is the struct of `internalChkCfg`, which holds the specific configurations for each lidar.
# Lidar type is configured in the second level (with 1 indention), while the detailed configuration for each lidar is configured in the third level (with 2 indentions).
internalChkCfg:
  L0110:
    lidarNo: 3   # lidar number. (see ./docs/lidarList.md)
    chTag: ['532p', '532s']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (days)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1800, 2000]   # [start index, stop index] for background correction
      nPretrigger: 0   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: false   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: true   # Rayleigh fit check
    flagBgNoiseChk: false   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    RayleighChkCfg:
      tRange: '2021-09-21 01:30:00 ~ 2021-09-21 02:00:00'
      wavelength:
        - [532]   # wavelength. (nm)
      fitRange:
        - [7000, 8000]   # Rayleigh fit range. (m)
      smoothwindow:
        - [300]
      MieGlue:
        - [1, 0]   # MieGlue * signal ([1, 0.5] * [PSignal, SSignal])
      hRange:
        - [0, 15000]   # display range. (m)
      sigRange:
        - [8e8, 1e12]   # signal display range. (a.u.)
      maxDev: [15]   # maximum relative deviation. (%)