################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

resultPath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\REAL
dataSavePath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\REAL
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  REAL:   # lidar No.1
    dataPath: D:\Data\CMA_Lidar_Comparison\internalChk\REAL\saturation-test
    dataFilenamePattern: .*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 5
    chTag: ['532sh', '532ph', '532sl', '532pl', '607l', '607h']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    nMaxBin: 2300   # number of bins

internalChkCfg:
  REAL:
    lidarNo: 11   # lidar number. (see ./docs/lidarList.md)
    chTag: ['532sh', '532ph', '532sl', '532pl', '607l', '607h']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: [3.5, 3.5, 3.5, 3.5, 3.5, 30.4]   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1700, 2000]   # [start index, stop index] for background correction
      nPretrigger: 55   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: true   # signal saturation check
    flagQuadrantChk: false   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: false   # Rayleigh fit check
    flagBgNoiseChk: false   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    saturationChkCfg:
      tRange:
        - '2021-09-27 16:23:00 ~ 2021-09-27 16:24:00'   # 100% transmission
        - '2021-09-27 16:26:00 ~ 2021-09-27 16:27:00'   # 80% transmission
        - '2021-09-27 16:27:00 ~ 2021-09-27 16:28:00'   # 50% transmission
        - '2021-09-27 16:28:00 ~ 2021-09-27 16:29:00'   # 20% transmission
        - '2021-09-27 16:30:00 ~ 2021-09-27 16:31:00'   # 10% transmission
      sigRange:
        - [1e10, 2e12]
        - [1e10, 1e14]
        - [1e8, 1e12]
        - [1e7, 1e13]
        - [1e7, 1e13]
        - [1e7, 1e13]
      hRange:
        - [0, 4000]
        - [0, 4000]
        - [0, 4000]
        - [0, 4000]
        - [0, 4000]
        - [0, 4000]
      normRange:
        - [500, 2000]
        - [500, 2000]
        - [500, 2000]
        - [500, 2000]
        - [500, 2000]
        - [500, 2000]
      maxDev: 
        - 10   # [%]
        - 10   # [%]
        - 10   # [%]
        - 10   # [%]
        - 10   # [%]
        - 10   # [%]
      smoothwindow: 
        - 300   # (m)
        - 300   # (m)
        - 300   # (m)
        - 300   # (m)
        - 300   # (m)
        - 300   # (m)