resultPath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\SY
dataSavePath: D:\Coding\Matlab\CMA-lidar-evaluation\lidar_evaluation\SY
figFormat: png   # figure format to be exported

dataLoaderCfg:
  SY:   # Shan yi suo
    dataPath: D:\Data\CMA_Lidar_Comparison\internalChk\SY\RayleighFit-test
    dataFilenamePattern: .*Lidar.*   # all files
    dataFormat: 3
    chTag: ['532p', '532s', '355e', '607', '1064e']
    nMaxBin: 1600   # number of bins
    flagFilenameTime: true

internalChkCfg:
  SY:
    lidarNo: 14   # lidar number. (see ./docs/lidarList.md)
    chTag: ['532p', '532s', '355e', '607', '1064e']
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1400, 1500]   # [start index, stop index] for background correction
      nPretrigger: 0   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: false   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: true   # Rayleigh fit check
    flagBgNoiseChk: false   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    RayleighChkCfg:
      tRange: '2021-09-23 05:12:00 ~ 2021-09-23 05:15:00'
      wavelength:
        - [1064]   # wavelength. (nm)
      fitRange:
        - [11000, 13000]   # Rayleigh fit range. (m)
      smoothwindow:
        - [300]
      MieGlue:
        - [0, 0, 0, 0, 1]   # MieGlue * signal ([1, 0.5] * [PSignal, SSignal])
      hRange:
        - [0, 15000]   # display range. (m)
      sigRange:
        - [2e5, 2e7]   # signal display range. (a.u.)
      maxDev: [15]   # maximum relative deviation. (%)
      flagLinearFit: true