################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

evaluationReportPath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation
dataSavePath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  WHULidar1064:   # lidar No.1
    dataPath: D:\Data\CMA_Lidar_Comparison\WHU1064\telecover_test2
    dataFilenamePattern: .*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 1
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    nMaxBin: 2048   # number of bins

internalChkCfg:
  WHULidar1064:
    lidarNo: 12   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1500, 2000]   # [start index, stop index] for background correction
      nPretrigger: 15   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: true   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: false   # Rayleigh fit check
    flagBgNoiseChk: false   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    quadrantChkCfg:
      quadrantTime:   # quadrant time (local time) [E-S-W-N-E]
        - '2021-09-25 23:12:00 ~ 2021-09-25 23:13:00'   # east1
        - '2021-09-25 23:13:20 ~ 2021-09-25 23:14:20'   # south
        - '2021-09-25 23:15:00 ~ 2021-09-25 23:16:00'   # west
        - '2021-09-25 23:16:00 ~ 2021-09-25 23:17:00'   # north
        - '2021-09-25 23:18:00 ~ 2021-09-25 23:19:00'   # east2
      hRangeNear: [0, 1000]   # vertical range for near-range behavior to display. (m)
      hRangeAll: [0, 5000]   # vertical range for overall behavior to display. (m)
      normRange: [500, 700]   # normalization range. (m)
      normSigDisplayRangeAll: [0, 5e8]   # normalized signal display range. (photon count)
      rcsDisplayRangeAll: [0, 1e10]   # normalized signal display range. (photon count)
      normSigDisplayRangeNear: [0, 5e8]   # normalized signal display range. (photon count)
      smoothwindow: 300   # smoothing window length. (m)
      stableThresh: 10   # [%]
      maxDev: 20   # [%]