################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

evaluationReportPath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation\WHU1064
dataSavePath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation\WHU1064
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  WHU1064:   # lidar No.1
    dataPath: D:\Data\CMA_Lidar_Comparison\WHU1064\background-noise
    dataFilenamePattern: .*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 1
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    nMaxBin: 2048   # number of bins

internalChkCfg:
  WHU1064:
    lidarNo: 12   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1500, 2000]   # [start index, stop index] for background correction
      nPretrigger: 15   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    fullOverlapHeight: 400   # minimum height with complete overlap. (m)
    flagRetrievalChk: false   # backscatter retrieval check
    flagSaturationChk: false   # signal saturation check
    flagQuadrantChk: false   # quadrant check
    flagOverlapChk: false   # overlap evaluation
    flagRayleighChk: false   # Rayleigh fit check
    flagBgNoiseChk: true   # background noise check
    flagDetectRangeChk: false   # detection ability check
    flagContOptChk: false   # continuous operation check
    bgNoiseChkCfg:
      closeTRange: '2021-09-27 17:13:00 ~ 2021-09-27 17:42:00'   # cover closed
      randErrCalcWindowLength: 150   # window length for calculating random error. (m)
      bgRange:
        - [-3, 3]
      hRange:   # background display range. (m)
        - [14000, 20000]