################################################################################
# lidar configuration file
# DON'T use Chinese characters!!!
################################################################################

evaluationReportPath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation\WHU1064_2
dataSavePath: D:\Coding\Matlab\lidar_evaluation_1064\lidar_evaluation\WHU1064_2
figFormat: png   # figure format to be exported

# data loader configuration
# Load lidar data to a specified directory (defined by `dataSavePath`)
dataLoaderCfg:
  WHULidar1064_2:   # lidar No.1
    dataPath: D:\Data\CMA_Lidar_Comparison\WHU1064_2\27
    dataFilenamePattern: .*   # all files
    # data type
    # 1: WHU standard 1064 nm lidar
    # 2: WHU non-standard 1064 nm lidar
    # 3: CMA standard data format in binary
    # 4: Dasun visibility lidar
    # 5: REAL
    dataFormat: 2
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    nMaxBin: 1300   # number of bins

dataVisualCfg:
  WHULidar1064_2:
    lidarNo: 13   # lidar number. (see ./docs/lidarList.md)
    chTag: ['1064e']   # 355e; 355p; 355s; 387; 407; 532e; 532p; 532s; 607; 1064e; 1064p; 1064s; 532pl; 532sl; 607l; 532ph; 532sh; 607h
    figVisible: 'on'   # whether display figures
    preprocessCfg:
      hOffset: 0   # height offset. (m)
      tOffset: 0   # time offset. (min)
      deadTime: []   # deadtime (ns). If it's empty, deadtime correction is disabled.
      bgBins: [1100, 1200]   # [start index, stop index] for background correction
      nPretrigger: 0   # if nPretrigger < 0, move signal up
      bgCorFile: ''   # data file of dark measurement results
      overlapFile: ''
    tRange: '2021-09-27 00:00:00 ~ 2021-09-27 23:59:00'
    hRange: [0, 14000]
    sigRange: [0, 0.7e9]
    title: 'WHU1064_2 2021-09-27'
    deltaT: 0.5   # temporal resolution (min)
    markTRange: ''