clc; close all;
global LEToolboxInfo

fprintf('background noise check for all lidars.\n');

configFiles = {...
    fullfile(LEToolboxInfo.projectDir, 'config', 'DS_background_noise_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'L7_background_noise_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'SY_background_noise_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'GB_background_noise_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'REAL_background_noise_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'WH1_background_noise_test_config.yml')...
    };

for iLidar = 1:length(configFiles)
    LEMain(configFiles{iLidar}, 'flagReadData', true, 'flagInternalChk', true);
end