close all;

LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\DS_background_config.yml', ...
    'flagReadData', true, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);
LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\DS_detectRangeChk_config.yml', ...
    'flagReadData', true, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);
LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\DS_RayleighFit_config.yml', ...
    'flagReadData', true, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);
LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\704_saturationChk_config.yml', ...
    'flagReadData', true, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);
LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\DS_telecover_test_config.yml', ...
    'flagReadData', true, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);