close all;

LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\externalChk_config.yml', ...
    'flagReadData', false, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);