close all;

LEMain('D:\Coding\Matlab\CMA-lidar-evaluation\config\external_check_config.yml', ...
    'flagReadData', true, ...
    'flagInternalChk', false, ...
    'flagExternalChk', false, ...
    'flagQL', true, ...
    'flagDebug', false);