close all;

LEMain('D:\Coding\Matlab\CMA-lidar-evaluation\config\external_check_config.yml', ...
    'flagReadData', false, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);