close all;

% LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\704_RayleighChk_config.yml', ...
%     'flagReadData', true, ...
%     'flagInternalChk', true, ...
%     'flagExternalChk', false, ...
%     'flagQL', false, ...
%     'flagDebug', false);
% LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\704_saturationChk_config.yml', ...
%     'flagReadData', true, ...
%     'flagInternalChk', true, ...
%     'flagExternalChk', false, ...
%     'flagQL', false, ...
%     'flagDebug', false);
LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\704_telecover_test_config.yml', ...
    'flagReadData', true, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);