clc; close all;
global LEToolboxInfo

fprintf('telecover test for all lidars.\n');

configFiles = {...
    fullfile(LEToolboxInfo.projectDir, 'config', 'DS_RayleighFit_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'AW_RayleighFit_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'GB_RayleighFit_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'REAL_RayleighFit_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'SY_RayleighFit_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'ZK_RayleighFit_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'WH2_RayleighFit_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'L7_RayleighFit_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'SS_RayleighFit_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'WH1_RayleighFit_test_config.yml')...
    };

for iLidar = 1:length(configFiles)
    LEMain(configFiles{iLidar}, 'flagReadData', true, 'flagInternalChk', true);
end