clc; close all;
global LEToolboxInfo

fprintf('saturation test for all lidars.\n');

configFiles = {...
    fullfile(LEToolboxInfo.projectDir, 'config', 'AW_saturation_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'GB_saturation_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'REAL_saturation_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'SY_saturation_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'ZK_saturation_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'L7_saturation_test_config.yml  ')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'SS_saturation_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'WH1_saturation_test_config.yml')...
    };

for iLidar = 1:length(configFiles)
    LEMain(configFiles{iLidar}, 'flagReadData', true, 'flagInternalChk', true);
end