close all;

% LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\sys_background_config.yml', ...
%     'flagReadData', true, ...
%     'flagInternalChk', true, ...
%     'flagExternalChk', false, ...
%     'flagQL', false, ...
%     'flagDebug', false);
% LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\sys_detectRangeChk_config.yml', ...
%     'flagReadData', true, ...
%     'flagInternalChk', true, ...
%     'flagExternalChk', false, ...
%     'flagQL', false, ...
%     'flagDebug', false);
% LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\sys_RayleighFit_config.yml', ...
%     'flagReadData', true, ...
%     'flagInternalChk', true, ...
%     'flagExternalChk', false, ...
%     'flagQL', false, ...
%     'flagDebug', false);
% LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\sys_saturation_config.yml', ...
%     'flagReadData', true, ...
%     'flagInternalChk', true, ...
%     'flagExternalChk', false, ...
%     'flagQL', false, ...
%     'flagDebug', false);
LEMain('D:\Coding\Matlab\lidar_evaluation_1064\config\sys_telecovertest_config.yml', ...
    'flagReadData', true, ...
    'flagInternalChk', true, ...
    'flagExternalChk', false, ...
    'flagQL', false, ...
    'flagDebug', false);