clc; close all;
global LEToolboxInfo

fprintf('telecover test for all lidars.\n');

configFiles = {...
    fullfile(LEToolboxInfo.projectDir, 'config', 'DS_telecover_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'AW_telecover_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'GB_telecover_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'REAL_telecover_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'SY_telecover_test_config.yml'), ...
    fullfile(LEToolboxInfo.projectDir, 'config', 'ZK_telecover_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'DS_telecover_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'L7_telecover_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'SS_telecover_test_config.yml')...
    fullfile(LEToolboxInfo.projectDir, 'config', 'WH1_telecover_test_config.yml')...
    };

for iLidar = 1:length(configFiles)
    LEMain(configFiles{iLidar}, 'flagReadData', true, 'flagInternalChk', true);
end